### ISSUE TITLE
Ideas for future features - epic

### ISSUE THREAD

**Issue by amis92** [BSData/catalogue-development#59]
Please post your ideas in comments.

Current list of asked features:

- [ ] Data localization: #15
- [ ] Unofficial/fanmade data hosting #5 
- [ ] Automated release story
- [ ] More integrations with issue reporting, with more details (discord bot, BS in-app report tool)
- [ ] Support for non-BSData repositories, may directly enable unofficial/fanmade data (#5)

**Comment by DarkSkyT9A** [comment]
Request for features:
- [ ] Allow categories to be dynamically changed by modifiers
- [ ] Remove mandatory force entry from GST or at least make the "hidden" flag do something.

**Comment by Guy-Markman** [comment]
CTRL + Z for data editor and maybe even roaster.

**Comment by amis92** [comment]
@Guy-Markman @DarkSkyT9A these requests are not so much for data itself, rather for BattleScribe *app*. What this was meant for are features for our *online* operations, features, how this organization works, sharing data, these kinds of things. For app-specific features, please post in https://github.com/BattleScribe/Release
